mixed-port: 7890
allow-lan: false
log-level: info
mode: rule
#external-controller: 127.0.0.1:9090

proxies:
  - name: "mohe"
    uuid: uuid
    type: vmess
    server: khamenei.ir
    port: 443
    alterId: 0
    cipher: auto
    tls: true
    network: ws
    ws-opts:
      path: /ray
      headers:
         Host: khamenei.ir

proxy-groups:
  - name: "auto"
    type: relay
    proxies:
      - "mohe"

rules:
  - MATCH,auto
